project:
  name: "lambda-test-python"
  description: "Simple Python Lambda function for testing the deploy action"
  runtime: "python"
  
  # Optional: Specify runtime versions
  versions:
    python: "3.9"

build:
  # Commands (use "auto" for automatic detection)
  commands:
    install: "pip install -r requirements.txt"
    lint: "auto"  # Will use flake8 if available
    test: "python -m unittest test_lambda.py -v"
    build: "auto"  # Will create zip automatically
  
  # Quality gates
  lint_required: false    # Optional for this simple example
  tests_required: true    # Ensure tests pass before deployment
  
  # Artifact configuration
  artifact:
    path: "lambda-deployment.zip"
    exclude_patterns:
      - "*.md"
      - "test_*.py"
      - "__pycache__/"
      - "*.pyc"
      - ".pytest_cache/"

# Deployment configuration
deployment:
  # Optional health check with comprehensive response validation
  health_check:
    # Enable health check
    enabled: true
    
    # Test payload options (choose one):
    
    # Option 1: YAML object format (recommended - cleaner, no JSON escaping)
    test_payload_object:
      name: "Test"
      source: "GitHub Actions"
      timestamp: "2025-08-22"
      environment: "dev"
    
    # Option 2: JSON string format (alternative)
    # test_payload: '{"name":"Test","source":"deployment"}'
    
    # Response validation options:
    
    # Expected HTTP status code (default: 200)
    expected_status_code: 200
    
    # Text that should be present in the response (checks both raw response and parsed body)
    expected_response_contains: "Hello, Test!"
    
    # Optional: Expected error message (for testing error scenarios)
    # Use this when you expect the Lambda to return an error
    # expected_error_message: "ValidationError"
    
    # Examples of different validation scenarios:
    
    # For successful responses:
    # expected_status_code: 200
    # expected_response_contains: "success"
    
    # For testing error handling:
    # expected_status_code: 400
    # expected_error_message: "Invalid input"
    
    # For API Gateway responses:
    # expected_status_code: 200
    # expected_response_contains: '"statusCode":200'

environments:
  dev:
    trigger_branches: 
      - "main"
      - "feature/**"
    aws:
      region: "eu-west-1"
      auth_type: "access_key"
    deployment:
      versioning: false
      run_tests: true
      notifications: false
  pre:
    trigger_branches:
      - "main"
      - "feature/**"
    aws:
      auth_type: "access_key"
    deployment:
      versioning: false
      run_tests: true
      notifications: false
  
  prod:
    aws:
      region: "eu-west-1"
      auth_type: "oidc"
    deployment:
      versioning: true
      run_tests: true
      notifications: true
      require_manual_approval: true
    notifications:
      teams:
        webhook_secret: "TEAMS_WEBHOOK_URL"