# Lambda deployment configuration for lambda-test-python
# Version managed in pyproject.toml (modern Python standard)

project:
  name: "lambda-test-python"
  description: "Simple Python Lambda function for testing the deploy action"
  runtime: "python"
  versions:
    python: "3.9"

build:
  commands:
    install: "pip install -r requirements.txt"
    # lint: "flake8 ."                    # Optional: Uncomment and install flake8 if needed
    # test: "python -m pytest tests/"    # Optional: Uncomment and install pytest if needed
    build: "auto"    # automatic packaging
  
  # Artifact configuration
  artifact:
    path: "lambda-deployment.zip"
    exclude_patterns:
      - "*.md"
      - "test_*.py"
      - "__pycache__/"
      - "*.pyc"
      - ".pytest_cache/"
      - "pyproject.toml"  # Exclude from deployment package

environments:
  dev:
    trigger_branches: ["main", "feature/**"]
    aws:
      region: "eu-west-1"
      auth_type: "access_key"
    deployment:
      versioning: false
      run_tests: true
      notifications: false

# Deployment configuration
deployment:
  # Health check configuration
  health_check:
    enabled: true
    test_payload_object:
      name: "Test"
      source: "GitHub Actions"
      timestamp: "2025-08-22"
      environment: "dev"
    expected_status_code: 200
    expected_response_contains: "Hello, Test!"

  # Auto-rollback configuration (choose your preference)
  auto_rollback:
    # OPTION 1: Disabled (default) - Manual rollback only
    enabled: false
    
    # OPTION 2: Enabled - Automatic rollback on deployment failure
    # enabled: true
    # strategy: "last_successful"
    # triggers:
    #   on_deployment_failure: true
    #   on_health_check_failure: false
    # behavior:
    #   max_attempts: 1
    #   validate_rollback: true
    #   fail_on_rollback_failure: true

# NOTE: Version is now managed in pyproject.toml
# The action will automatically detect and use the version from:
# [project]
# version = "1.0.0"

# For advanced usage with development dependencies, see:
# lambda-deploy-config-with-pyproject.yml
